# api-reference-mask.awk
#
# Masks the Unity-IAP-conditional public surface out of Documentation~/api-reference.md so the
# committed file (generated by a developer whose project has com.unity.purchasing compiled) can be
# diffed against a CI regeneration (game-ci base image has NO Unity.Purchasing.dll, so the
# `#if UNITY_PURCHASING_INSTALLED` members compile out). Applied to BOTH sides before the diff in
# .github/workflows/docs-check.yml. It is NOT used by build-docs.sh - the committed artifact keeps
# the full, purchasing-inclusive documentation.
#
# What is masked (the complete, enumerable conditional set as of SDK 4.0.0):
#   1. The AttachPurchaseTracking(StoreController) member section (heading-delimited).
#   2. Any TrackPurchase(...) cross-reference, whose overload target resolves differently depending
#      on whether TrackPurchase(PendingOrder) compiled.
#
# When a NEW purchasing-gated public member is added, this mask will not know about it: the CI diff
# will go RED (the member is in the dev file but not the CI regen). That is intentional and safe -
# a human extends this mask in the same change, consciously. The failure is visible, never silent.
{ line = $0 }
/^#### AttachPurchaseTracking\(StoreController\)/ { skip = 1; next }
skip == 1 && /^#{2,4} / { skip = 0 }
skip == 1 { next }
{ gsub(/TrackPurchase\([^)]*\)/, "TrackPurchase(MASKED)", line); print line }
