using System.IO;
using System.Linq;
using UnityEngine;

#if UNITY_ANDROID
using UnityEditor.Android;

namespace Sorolla.Palette.Editor
{
    /// <summary>
    ///     Post-export Gradle project fixes:
    ///     1. Patch auto-generated manifests (delegated to AndroidManifestSanitizer)
    ///     2. Re-enable DexingArtifactTransform (pre-Unity 6)
    /// </summary>
    public class GradlePropertiesFixer : IPostGenerateGradleAndroidProject
    {
        private const string Tag = "[Palette GradleFixer]";
        private const string DexingProperty = "android.enableDexingArtifactTransform";

        // Run after AppLovin (int.MaxValue - 10)
        public int callbackOrder => int.MaxValue;

        public void OnPostGenerateGradleAndroidProject(string path)
        {
            AndroidManifestSanitizer.FixAutoGeneratedLauncherManifest(path);
            AndroidManifestSanitizer.StripLibraryLauncherIntent(path);
            AndroidManifestSanitizer.EnsureConsentModeDefaults(path);

#if !UNITY_6000_0_OR_NEWER
            FixDexingArtifactTransform(path);
#endif
        }

        private static void FixDexingArtifactTransform(string path)
        {
            // path points to unityLibrary — gradle.properties is one level up
            var gradlePropertiesPath = Path.GetFullPath(Path.Combine(path, "..", "gradle.properties"));

            if (!File.Exists(gradlePropertiesPath))
            {
                Debug.LogWarning($"{Tag} gradle.properties not found, skipping dexing fix");
                return;
            }

            var lines = File.ReadAllLines(gradlePropertiesPath);
            var updated = lines
                .Where(line => !line.Contains(DexingProperty))
                .ToList();

            updated.Add($"{DexingProperty}=true");

            File.WriteAllText(gradlePropertiesPath, string.Join("\n", updated) + "\n");
            Debug.Log($"{Tag} Enabled DexingArtifactTransform (overriding AppLovin legacy dexing)");
        }
    }
}
#endif
